version: '3.1'

networks:
  trademarks:

services:

  server:
    restart: always
    environment:
      - HTTP_ADDR=:1323 
      - PG_URL=postgres://postgres:postgres@postgres/db_trademarks?sslmode=disable
      - LOG_LEVEL=debug
      - PG_MIGRATIONS_PATH=file://../../migrations
    build: ./
    command: ["./server"]
    ports:
      - 1323:1323
    depends_on:
      - postgres
    networks:
      - trademarks

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_trademarks
    ports:
      - 5432:5432
    networks:
      - trademarks

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - trademarks

